In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/results.csv')
display(df.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [ ]:
# Convert 'date' column to datetime objects
df['date'] = pd.to_datetime(df['date'])

In [ ]:
# Filter the DataFrame to keep rows where the year is between 2023 and 2026
df_filtered = df[(df['date'].dt.year >= 2023) & (df['date'].dt.year <= 2026)]

display(df_filtered.head())

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
45807,2023-01-02,Thailand,Cambodia,3.0,1.0,AFF Championship,Pathum Thani,Thailand,False
45808,2023-01-02,Philippines,Indonesia,1.0,2.0,AFF Championship,Manila,Philippines,False
45809,2023-01-03,Vietnam,Myanmar,3.0,0.0,AFF Championship,Hanoi,Vietnam,False
45810,2023-01-03,Malaysia,Singapore,4.0,1.0,AFF Championship,Kuala Lumpur,Malaysia,False
45811,2023-01-06,Iraq,Oman,0.0,0.0,Gulf Cup,Basra,Iraq,False

In [ ]:
df_filtered = df_filtered.drop(columns=['city', 'country', 'neutral'])
display(df_filtered.head())

,date,home_team,away_team,home_score,away_score,tournament
45807,2023-01-02,Thailand,Cambodia,3.0,1.0,AFF Championship
45808,2023-01-02,Philippines,Indonesia,1.0,2.0,AFF Championship
45809,2023-01-03,Vietnam,Myanmar,3.0,0.0,AFF Championship
45810,2023-01-03,Malaysia,Singapore,4.0,1.0,AFF Championship
45811,2023-01-06,Iraq,Oman,0.0,0.0,Gulf Cup

In [ ]:
def get_winner(row):
    if row['home_score'] > row['away_score']:
        return row['home_team']
    elif row['away_score'] > row['home_score']:
        return row['away_team']
    else:
        return 'Draw'

df_filtered['winner'] = df_filtered.apply(get_winner, axis=1)
display(df_filtered.head())

,date,home_team,away_team,home_score,away_score,tournament,winner
45807,2023-01-02,Thailand,Cambodia,3.0,1.0,AFF Championship,Thailand
45808,2023-01-02,Philippines,Indonesia,1.0,2.0,AFF Championship,Indonesia
45809,2023-01-03,Vietnam,Myanmar,3.0,0.0,AFF Championship,Vietnam
45810,2023-01-03,Malaysia,Singapore,4.0,1.0,AFF Championship,Malaysia
45811,2023-01-06,Iraq,Oman,0.0,0.0,Gulf Cup,Draw

In [ ]:
from google.colab import files

df_filtered.to_csv('df_filtered.csv', index=False)
files.download('df_filtered.csv')