In [ ]:
import pandas as pd

file_path = '/content/whoscored_player_stats_passing.csv'
df = pd.read_csv(file_path)
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,...,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,passSuccess,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,True,36,247,cint,International,FIFA World Cup,7.320000,90,92.000000,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,True,5,108,it,Italy,Serie A,7.054483,2551,85.584219,2
2,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,86.486486,3
3,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),...,True,22,74,fr,France,Ligue 1,6.780000,90,95.121951,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,False,60,108,it,Italy,Coppa Italia,0.000000,0,0.000000,5

In [ ]:
pd.set_option('display.max_columns', None)
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,teamRegionName,regionCode,tournamentShortName,apps,subOn,assistTotal,keyPassPerGame,totalPassesPerGame,accurateCrossesPerGame,accurateLongPassPerGame,accurateThroughBallPerGame,name,firstName,lastName,playerId,positionText,teamId,teamName,seasonId,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,passSuccess,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WC,1,0,1,2.000000,50.000000,0.000000,5.000000,1.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10498,2026,True,36,247,cint,International,FIFA World Cup,7.320000,90,92.000000,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISA,29,1,4,0.931034,45.448276,0.551724,1.620690,0.034483,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10732,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,85.584219,2
2,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WCQ,3,2,0,1.333333,24.666667,0.333333,0.333333,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10555,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,86.486486,3
3,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),France,fr,FL1,1,0,0,4.000000,41.000000,3.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,249,Marseille,10792,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,95.121951,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ICI,2,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10773,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,0.000000,5

In [ ]:
columns_to_drop = [
    'height',
    'weight',
    'age',
    'isManOfTheMatch',
    'isActive',
    'playedPositions',
    'playedPositionsShort',
    'teamRegionName',
    'regionCode',
    'tournamentShortName',
    'subOn',
    'name',
    'firstName',
    'lastName',
    'playerId',
    'teamId',
    'teamName',
    'seasonId',
    'seasonName',
    'isOpta',
    'tournamentId',
    'tournamentRegionId',
    'tournamentRegionCode',
    'tournamentRegionName',
    'tournamentName',
    'minsPlayed',
    'ranking'
]

df = df.drop(columns=columns_to_drop)
display(df.head())

,Player_ID,Team_Name,Player_Name,apps,assistTotal,keyPassPerGame,totalPassesPerGame,accurateCrossesPerGame,accurateLongPassPerGame,accurateThroughBallPerGame,positionText,rating,passSuccess
0,116609,France,Adrien Rabiot,1,1,2.000000,50.000000,0.000000,5.000000,1.000000,Midfielder,7.320000,92.000000
1,116609,France,Adrien Rabiot,29,4,0.931034,45.448276,0.551724,1.620690,0.034483,Midfielder,7.054483,85.584219
2,116609,France,Adrien Rabiot,3,0,1.333333,24.666667,0.333333,0.333333,0.000000,Midfielder,6.903333,86.486486
3,116609,France,Adrien Rabiot,1,0,4.000000,41.000000,3.000000,0.000000,0.000000,Midfielder,6.780000,95.121951
4,116609,France,Adrien Rabiot,2,0,0.000000,0.000000,0.000000,0.000000,0.000000,Midfielder,0.000000,0.000000

In [ ]:
aggregation_functions = {
    'apps': 'sum',
    'assistTotal': 'sum',
    'keyPassPerGame': lambda x: x[x != 0].mean(),
    'totalPassesPerGame': lambda x: x[x != 0].mean(),
    'accurateCrossesPerGame': lambda x: x[x != 0].mean(),
    'accurateLongPassPerGame':lambda x: x[x != 0].mean(),
    'accurateThroughBallPerGame': lambda x: x[x != 0].mean(),
    'rating': lambda x: x[x != 0].mean(),
    'passSuccess': lambda x: x[x != 0].mean()
}

df_agg = df.groupby(['Player_ID', 'Team_Name', 'Player_Name']).agg(aggregation_functions).reset_index()
display(df_agg.head())

,Player_ID,Team_Name,Player_Name,apps,assistTotal,keyPassPerGame,totalPassesPerGame,accurateCrossesPerGame,accurateLongPassPerGame,accurateThroughBallPerGame,rating,passSuccess
0,5583,Portugal,Cristiano Ronaldo,38,0,0.200000,18.600000,0.200000,0.600000,NaN,7.006000,91.397849
1,8280,Scotland,Craig Gordon,8,0,NaN,27.666667,NaN,6.055556,NaN,6.412778,52.843902
2,11119,Argentina,Lionel Messi,41,8,2.516667,42.352381,1.092857,1.976190,0.642857,7.812119,83.431002
3,13754,Germany,Manuel Neuer,43,0,NaN,30.779545,NaN,6.434091,NaN,6.387705,81.135790
4,20874,Croatia,Luka Modric,55,5,1.097222,46.213235,0.687092,2.975490,0.264706,6.715343,89.435256

In [ ]:
from google.colab import files

output_filename = 'whoscored_player_stats_passing_processed.csv'
df_agg.to_csv(output_filename, index=False)
files.download(output_filename)