In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/whoscored_player_stats.csv')
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,teamRegionName,regionCode,tournamentShortName,apps,subOn,manOfTheMatch,goal,assistTotal,shotsPerGame,aerialWonPerGame,name,firstName,lastName,playerId,positionText,teamId,teamName,seasonId,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,yellowCard,redCard,passSuccess,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISA,29,1,4,6,4,1.586207,1.517241,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10732,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,4.0,1.0,85.584219,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WCQ,3,2,0,1,0,1.000000,1.666667,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10555,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,1.0,0.0,86.486486,2
2,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),France,fr,FL1,1,0,0,0,0,1.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,249,Marseille,10792,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,1.0,0.0,95.121951,3
3,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ICI,2,0,0,0,0,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10773,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,0.0,0.0,0.000000,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISC,1,0,0,0,0,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10897,2024/2025,False,64,108,it,Italy,Supercoppa Italiana,0.000000,0,1.0,0.0,0.000000,5

In [ ]:
pd.set_option('display.max_columns', None)
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,teamRegionName,regionCode,tournamentShortName,apps,subOn,manOfTheMatch,goal,assistTotal,shotsPerGame,aerialWonPerGame,name,firstName,lastName,playerId,positionText,teamId,teamName,seasonId,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,yellowCard,redCard,passSuccess,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISA,29,1,4,6,4,1.586207,1.517241,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10732,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,4.0,1.0,85.584219,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WCQ,3,2,0,1,0,1.000000,1.666667,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10555,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,1.0,0.0,86.486486,2
2,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),France,fr,FL1,1,0,0,0,0,1.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,249,Marseille,10792,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,1.0,0.0,95.121951,3
3,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ICI,2,0,0,0,0,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10773,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,0.0,0.0,0.000000,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISC,1,0,0,0,0,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10897,2024/2025,False,64,108,it,Italy,Supercoppa Italiana,0.000000,0,1.0,0.0,0.000000,5

In [ ]:
columns_to_drop = [
    'height', 'weight', 'age', 'isManOfTheMatch', 'isActive', 'minsPlayed',
    'playedPositions', 'playedPositionsShort', 'teamRegionName',
    'regionCode', 'tournamentShortName', 'subOn', 'name',
    'firstName', 'lastName', 'playerId', 'teamId', 'teamName',
    'seasonId', 'seasonName', 'isOpta', 'tournamentId',
    'tournamentRegionId', 'tournamentRegionCode', 'tournamentRegionName',
    'tournamentName', 'ranking'
]
df = df.drop(columns=columns_to_drop)
display(df.head())

,Player_ID,Team_Name,Player_Name,apps,manOfTheMatch,goal,assistTotal,shotsPerGame,aerialWonPerGame,positionText,rating,yellowCard,redCard,passSuccess
0,116609,France,Adrien Rabiot,29,4,6,4,1.586207,1.517241,Midfielder,7.054483,4.0,1.0,85.584219
1,116609,France,Adrien Rabiot,3,0,1,0,1.000000,1.666667,Midfielder,6.903333,1.0,0.0,86.486486
2,116609,France,Adrien Rabiot,1,0,0,0,1.000000,0.000000,Midfielder,6.780000,1.0,0.0,95.121951
3,116609,France,Adrien Rabiot,2,0,0,0,0.000000,0.000000,Midfielder,0.000000,0.0,0.0,0.000000
4,116609,France,Adrien Rabiot,1,0,0,0,0.000000,0.000000,Midfielder,0.000000,1.0,0.0,0.000000

In [ ]:
aggregation_functions = {
    'apps': 'sum',
    'manOfTheMatch': 'sum',
    'goal': 'sum',
    'assistTotal': 'sum',
    'yellowCard': 'sum',
    'redCard': 'sum',
    'shotsPerGame': lambda x: x[x != 0].mean(),
    'aerialWonPerGame': lambda x: x[x != 0].mean(),
    'passSuccess': lambda x: x[x != 0].mean(),
    'rating': lambda x: x[x != 0].mean()
}

df_aggregated = df.groupby(['Player_ID', 'Player_Name']).agg(aggregation_functions).reset_index()
display(df_aggregated.head())

,Player_ID,Player_Name,apps,manOfTheMatch,goal,assistTotal,yellowCard,redCard,shotsPerGame,aerialWonPerGame,passSuccess,rating
0,5583,Cristiano Ronaldo,38,0,33,0,2.0,1.0,6.200000,0.800000,91.397849,7.006000
1,8280,Craig Gordon,9,0,0,0,0.0,0.0,NaN,0.444444,52.843902,6.412778
2,11119,Lionel Messi,41,12,25,8,3.0,0.0,3.950000,0.171429,83.431002,7.812119
3,13754,Manuel Neuer,43,0,0,0,3.0,0.0,NaN,0.045455,79.393175,6.393606
4,20874,Luka Modric,55,4,4,5,4.0,0.0,0.876634,0.411765,89.435256,6.715343

In [ ]:
df_aggregated.to_csv('df_aggregated.csv', index=False)
print('df_aggregated.csv has been downloaded.')

df_aggregated.csv has been downloaded.