In [ ]:
import pandas as pd

file_path = '/content/whoscored_player_stats_offensive.csv'
df = pd.read_csv(file_path)
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,...,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,2
2,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),...,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,3
3,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),...,2024/2025,False,64,108,it,Italy,Supercoppa Italiana,0.000000,0,5

In [ ]:
pd.set_option('display.max_columns', None)
display(df.head())

,Player_ID,Team_Name,Player_Name,height,weight,age,isManOfTheMatch,isActive,playedPositions,playedPositionsShort,teamRegionName,regionCode,tournamentShortName,apps,subOn,goal,assistTotal,shotsPerGame,keyPassPerGame,dribbleWonPerGame,foulGivenPerGame,offsideGivenPerGame,dispossessedPerGame,turnoverPerGame,name,firstName,lastName,playerId,positionText,teamId,teamName,seasonId,seasonName,isOpta,tournamentId,tournamentRegionId,tournamentRegionCode,tournamentRegionName,tournamentName,rating,minsPlayed,ranking
0,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISA,29,1,6,4,1.586207,0.931034,0.689655,1.896552,0.241379,1.137931,1.517241,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10732,2025/2026,True,5,108,it,Italy,Serie A,7.054483,2551,1
1,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),France,fr,WCQ,3,2,1,0,1.000000,1.333333,0.666667,1.000000,0.000000,0.666667,0.333333,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,341,France,10555,2025/2026,True,721,247,cint,International,World Cup Qualification UEFA,6.903333,104,2
2,116609,France,Adrien Rabiot,191,86,31,False,False,-MC-ML-,M(CL),France,fr,FL1,1,0,0,0,1.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,249,Marseille,10792,2025/2026,True,22,74,fr,France,Ligue 1,6.780000,90,3
3,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ICI,2,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10773,2025/2026,False,60,108,it,Italy,Coppa Italia,0.000000,0,4
4,116609,France,Adrien Rabiot,191,86,31,False,True,-MC-ML-,M(CL),Italy,fr,ISC,1,0,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Adrien Rabiot,Adrien,Rabiot,116609,Midfielder,80,AC Milan,10897,2024/2025,False,64,108,it,Italy,Supercoppa Italiana,0.000000,0,5

In [ ]:
columns_to_drop = [
    'height',
    'weight',
    'age',
    'isManOfTheMatch',
    'isActive',
    'playedPositions',
    'playedPositionsShort',
    'teamRegionName',
    'regionCode',
    'tournamentShortName',
    'subOn',
    'name',
    'firstName',
    'lastName',
    'playerId',
    'positionText',
    'teamId',
    'teamName',
    'seasonId',
    'seasonName',
    'isOpta',
    'tournamentId',
    'tournamentRegionId',
    'tournamentRegionCode',
    'tournamentRegionName',
    'tournamentName',
    'minsPlayed',
    'ranking'
]

df = df.drop(columns=columns_to_drop, errors='ignore')
display(df.head())

,Player_ID,Team_Name,Player_Name,apps,goal,assistTotal,shotsPerGame,keyPassPerGame,dribbleWonPerGame,foulGivenPerGame,offsideGivenPerGame,dispossessedPerGame,turnoverPerGame,rating
0,116609,France,Adrien Rabiot,29,6,4,1.586207,0.931034,0.689655,1.896552,0.241379,1.137931,1.517241,7.054483
1,116609,France,Adrien Rabiot,3,1,0,1.000000,1.333333,0.666667,1.000000,0.000000,0.666667,0.333333,6.903333
2,116609,France,Adrien Rabiot,1,0,0,1.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,6.780000
3,116609,France,Adrien Rabiot,2,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,116609,France,Adrien Rabiot,1,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
aggregation_functions = {
    'apps': 'sum',
    'goal': 'sum',
    'assistTotal': 'sum',
    'shotsPerGame': lambda x: x[x != 0].mean(),
    'keyPassPerGame': lambda x: x[x != 0].mean(),
    'dribbleWonPerGame': lambda x: x[x != 0].mean(),
    'foulGivenPerGame': lambda x: x[x != 0].mean(),
    'offsideGivenPerGame': lambda x: x[x != 0].mean(),
    'dispossessedPerGame': lambda x: x[x != 0].mean(),
    'turnoverPerGame': lambda x: x[x != 0].mean(),
    'rating': lambda x: x[x != 0].mean()
}

df_aggregated = df.groupby(['Player_ID', 'Team_Name', 'Player_Name']).agg(aggregation_functions).reset_index()
display(df_aggregated.head())

,Player_ID,Team_Name,Player_Name,apps,goal,assistTotal,shotsPerGame,keyPassPerGame,dribbleWonPerGame,foulGivenPerGame,offsideGivenPerGame,dispossessedPerGame,turnoverPerGame,rating
0,5583,Portugal,Cristiano Ronaldo,38,33,0,6.200000,0.200000,NaN,NaN,1.000000,0.600000,0.600000,7.006000
1,8280,Scotland,Craig Gordon,8,0,0,NaN,NaN,NaN,0.333333,NaN,NaN,0.500000,6.412778
2,11119,Argentina,Lionel Messi,41,25,8,3.950000,2.516667,2.609524,1.604762,0.454762,2.223810,1.290476,7.812119
3,13754,Germany,Manuel Neuer,43,0,0,NaN,NaN,0.090909,0.393939,NaN,NaN,NaN,6.387705
4,20874,Croatia,Luka Modric,55,4,5,0.876634,1.097222,0.437500,0.545752,NaN,0.301471,0.613562,6.715343

In [ ]:
output_file_name = 'whoscored_player_stats_offensive_aggregated.csv'
df_aggregated.to_csv(output_file_name, index=False)

from google.colab import files
files.download(output_file_name)